### ISSUE TITLE
Add explicit MIT License to source dist

### ISSUE THREAD

**Issue by pmlandwehr** [jaraco/portend#3]
Hey-lo,

I'm building a version of `portend` using [`conda`](http://conda.pydata.org/) for [conda-forge](http://conda-forge.github.io/). When possible, we try to include a link to the license file in the `meta.yaml` specification for the build; doing so requires an actual license file be bundled with the dist and (usually) that said license be indexed in an explicit [`MANIFEST.in`](https://docs.python.org/2/distutils/sourcedist.html#manifest-related-options) file so that it gets included in the source distribution.

Would you consider adding a full copy of the MIT License to the bundle, along with an appropriate manifest?

**Comment by jaraco** [comment]
Hi. Per jaraco/skeleton#1, I avoid bundling a license file. I recommend that the builder recipe for conda-forge could rely on the license declared in the metadata either to bundle the license at build time or to rely simply on the license declaration in the package metadata.
