### ISSUE TITLE
Release 2.4 is not uploaded to pypi

### ISSUE THREAD

**Issue by scarabeusiv** [jaraco/portend#9]
As per $SUBJ, it should probably be sent there :)

**Comment by jaraco** [comment]
Hmm. [A test failed](https://travis-ci.org/jaraco/portend/jobs/463944678), so the release was not run.

**Comment by jaraco** [comment]
I've retagged 2.4 against 0779394 and expect it to pass tests and release.

**Comment by jaraco** [comment]
Confirmed released.
